name: update halal
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python scraper.py
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add halal_pairs.json
          git commit -m "update" || exit 0
          git push
